### ISSUE TITLE
Modularize dispatch.py into a package and script file(s)

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#24]

**Comment by ttimbers** [comment]
https://github.ubc.ca/UBC-DSCI/dsci-100-instructor/blob/master/src/dispatch.py

**Comment by trevorcampbell** [comment]
I'm copying the issue thread from the instructor github regarding `dispatch.py` here. This is basically a stream of consciousness that we should parse out into separate github issues.

- make it so that the script doesn't break when instructors work in their `dsci-100-instructor` folder, change branches, etc. i.e., somehow do all the auto-stuff in one folder hidden to instructors and then for manual grading move stuff into their folders.

- make it so that (ideally) nobody has to remember to keep the dsci-100-instructor repo where the autograder works `git pull`ed, or at most just the instructor has to remember to do this

- modularize the code. Right now it's just a big script with lots of ifs etc. It works, but probably easy to break it /unintended bugs when things go slightly wrong.

- make sure the students submitted/ folder doesn't have an html file with the same name as the worksheet/tutorial. nbgrader feedback breaks if html file of ipynb with the same name is in the students submitted directory. See #89

- make it so that solutions get returned right after deadlines, and feedback gets returned student-by-student if possible (i.e. don't wait for everyone to start returning feedback)

- keep track of the state of each assignment and only do processing steps that have not yet finished

- wrap everything in a try except block. If there's an uncaught exception, send an email to the instructor with the traceback

- don't output messages for any submission that has been handled

We also need to fix this: Formgrader Interface Does Not Follow Principle of Least Surprise - W2020 #194

Basically TAs didn't realize that when all grades are inputted for a student, that student is considered "graded" and things move on to the next stage.

We need to implement some sort of "diff" type checking to see if grading has been updated, and if so, see what stage of the grading process the "diff" happened at and restart the process from there (per student obviously)

- automate the generation of each worksheet/tutorial and push to github.com 30 mins before class!
@ttimbers commented: brilliant idea!!!! This could be easily done if we move the instructor repo to GitHub.com... I have been exploring GitHub Actions for CI/CD and other automating things and it's quite simple and amazing. We should think about this more...

- automate setting assignment dates, percentage pts = 100
- automate special centre for accessibility time extensions on quizzes etc?

From #190 : It's hard to ensure that all TAs/instructors/graders maintain their databases / repositories perfectly, and remember to keep them updated and on the right branch.

We should instead have a single repo stored at the admin account's home, automatically run git pull with an ssh key, copy in student files, run the autograder, copy the entire repository to the grader's folder, then when they're done grading run nbgrader export on the relevant database and import the results into the centralized db.

- for late assignments, either
a) have students email dscibot, which triggers a regrade. They get one shot and it's out of 50%
b) run one single regrade pass on all assignments / students at the end of the semester, taking the maximum of (original on-time grade, 50% late graded)

When student notebooks kill the kernel / otherwise fail, just give a 0

For example, I got the below error:
```
[AutogradeApp | INFO] Executing notebook with kernel: ir
Error: C stack usage  7971476 is too close to the limit
Execution halted
[AutogradeApp | ERROR] Kernel died while waiting for execute reply.
[AutogradeApp | ERROR] While processing assignment /home/jupyter/submitted/student_4710/worksheet_10, the kernel became unresponsive and we could not interrupt it. This probably means that the students' code has an infinite loop that consumes a lot of memory or something similar. nbgrader doesn't know how to deal with this problem, so you will have to manually edit the students' code (for example, to just throw an error rather than enter an infinite loop).
[AutogradeApp | WARNING] Removing failed assignment: /home/jupyter/autograded/student_4710/worksheet_10
[AutogradeApp | ERROR] There was an error processing assignment 'worksheet_10' for student 'student_4710'
[AutogradeApp | ERROR] Please see the the above traceback for details on the specific errors on the above failures.
Traceback (most recent call last):
  File "dispatch.py", line 814, in <module>
    dispatch(dsci100)
  File "dispatch.py", line 677, in dispatch
    autograde_assignment(course, anm, stu, grader)
  File "dispatch.py", line 286, in autograde_assignment
    subprocess.check_output(docker_command.split(' '))
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'run', '--rm', '-v', '/tank/home/dsci100/tdjc/dsci-100-instructor:/home/jupyter', 'ubcdsci/r-dsci-grading', 'nbgrader', 'autograde', '--assignment=worksheet_10', '--student=student_4710']' returned non-zero exit status 1.

```
And because I use `subprocess` to call docker, and docker returns a nonzero exit status, dispatch fails to continue.

currently my solution is to just manually input a grade of 0 on canvas -- it stops the autograder from trying to work on their assignment entirely

wrap the whole thing in a try block and if an uncaught exception happens email the instructor

have a named "page" or assignment or something on canvas where the instructor can input TA cwls and student extensions for grading, and have dispatch read that assignment's text to know who is grading who. That way they don't have to edit the dispatch script directly.

**Comment by trevorcampbell** [comment]
I did most of these things in rudaux -- making new issues for any remaining ideas
