### ISSUE TITLE
Create open/public Canvas course shell for testing

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#26]

**Comment by daisymzhang** [comment]
@ttimbers Can you perhaps export the current dummy course on UBC canvas so that I can import it to the one I created at https://canvas.instructure.com/courses/2034800/

**Comment by daisymzhang** [comment]
@ttimbers 
I am also not sure about which license to choose to publish the canvas course shell in; is this https://creativecommons.org/licenses/by-sa/4.0/ ok? It's easy enough to create another course & do it properly. At the moment I published it here: https://lor.instructure.com/resources/3eabd110069e461094a043b016e739cd?shared.

I suspect that we should also use a dsci email address instead of my personal email address to administer the course shell.

**Comment by ttimbers** [comment]
OK, I created a course shell and added @daisymzhang @trevorcampbell and I as Instructors, and @jyoo980 as a student.

**Comment by ttimbers** [comment]
this is done
