### ISSUE TITLE
Used shared EFS storage for both hubs

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#38]
We want to be able to use EFS storage so we can mount the same storage to both hubs. This means that we will not have to secure copy the assignments between hubs.

**Comment by hsmohammed** [comment]
Since we have both on the same availability zone, it should be straight forward. We will create the EFS and mount it to both EC2 instances. The steps of mounting EFS to EC2 instances can be found [here](https://docs.aws.amazon.com/efs/latest/ug/wt1-test.html).
We will need to decide on some choices we have for the EFS such as,
1- The choice of making it Infrequent Access or standard storage. For Infrequent Access reduces storage cost for files that are infrequently accessed.
2- The throughput mode for the EFS. There is the standard or the bursting modes, which determines the throughput (MiB/s) of storage. More information can be found [here](https://docs.aws.amazon.com/efs/latest/ug/performance.html)
3- File encryption at rest. More information [here](https://docs.aws.amazon.com/efs/latest/ug/encryption.html).

**Comment by ttimbers** [comment]
@lourenzutti - can you please help me setup the course workflow AWS permissions (specifically user named Hossam in our org) to use/add EFS to EC2 instances?

**Comment by Lourenzutti** [comment]
Sure. 

I added a policy to your account @hsmohammed can you try now? 

It might take some rounds for us to figure this out.

**Comment by hsmohammed** [comment]
Hi @Lourenzutti,

Thanks for your reply. I have logged into the AWS console, but I still don't have access to create/add EFS.

**Comment by hsmohammed** [comment]
Hi @Lourenzutti,

I checked now and I have the permission to use EFS.
Thanks!

**Comment by ttimbers** [comment]
@hsmohammed - now that we have persistent storage on both hubs, we need to figure out how to mount the student hub zfs filesystem onto the grading hub.

**Comment by trevorcampbell** [comment]
I'm closing this since NFS seems to be the way to go after recent testing. @ttimbers feel free to reopen if you don't agree.
